[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
