services:
  - type: web
    name: license-management-system
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FIREBASE_CREDENTIALS_PATH
        value: /opt/render/project/src/backend/firebase-credentials.json
    healthCheckPath: /admin/login

databases:
  - name: license-system-db
    plan: free
    databaseName: license_system
    user: license_user
